### ISSUE TITLE
Fails to run against the ChromeOS kernel

### ISSUE THREAD

**Issue by steev** [mmind/mali-driver#1]
The check in the update-mali-driver script looks for /sys/firmware/devicetree/base/compatible to check that the device is rockchip based.

On a ChromeOS kernel, that file doesn't exist, however, /proc/device-tree/compatible has the same information.

I'm working on a patch for this at the moment, that will run the /sys check, and if that fails, fall back to looking in /proc.  Probably not the best, or cleanest, but with just the proc check, it works here on the ChromeOS kernel.

**Comment by mmind** [comment]
This was fixed by the pull request from steev.
