### ISSUE TITLE
Name of package

### ISSUE THREAD

**Issue by steev** [mmind/mali-driver#2]
In the debian packaging this is called "mali-driver" however there's currently only support for veyron devices.  Would you be against re-naming it to mali-driver-veyron?  I'd like to add one based off this for the exynos machines, but the name would obviously conflict.

**Comment by mmind** [comment]
Hi, actually as you can see in the script, it already tries to determine the machine type by reading the devicetree data and downloads an appropriate mali package. So there is most likely no need to have a separate package for rk3288/exynos/etc, instead only the necessary hools for the exynos machines needs to be added. (and veyron is to specific in any case, as the binary blob runs fine on other rk3288 systems too :-) )

**Comment by steev** [comment]
Indeed, I'll look into adding exynos support as well.  I thought about it after I'd opened the issue.
